apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: nextjs
spec:
  args:
    - name: service
      description: Name of the Kubernetes Service to query
  metrics:
    - name: http-success
      interval: 1m                           # Sample every 1 minute :contentReference[oaicite:0]{index=0}
      count: 5                               # Require 5 consecutive samples :contentReference[oaicite:1]{index=1}
      successCondition: result[0] >= 0.99    # ≥99% success rate :contentReference[oaicite:2]{index=2}
      failureLimit: 1                        # Fail on first breach :contentReference[oaicite:3]{index=3}
      provider:
        prometheus:
          address: http://prometheus.monitoring.svc:9090
          query: |
            sum(rate(istio_requests_total{
              destination_service=~"{{args.service}}",
              response_code!~"5.*"
            }[2m])) 
            / sum(rate(istio_requests_total{
              destination_service=~"{{args.service}}"
            }[2m]))                  # Success rate over 2m window :contentReference[oaicite:4]{index=4}