name: "Lint and Test"
description: "Runs linting and unit tests"
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '18.x'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
    - name: Install
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm test -- --ci