name: AI-Powered Test Generation

on:
  pull_request:

jobs:
  generate-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Tests via AI
        uses: markaicode/nodejs-cicd-ai-test-generation@v1 # AI test gen for Node.js projects :contentReference[oaicite:9]{index=9}
        with:
          openai-token: ${{ secrets.OPENAI_API_KEY }}
          source-path: "src/"
          output-path: "__generated_tests__/"
      - name: Run Generated Tests
        run: |
          npm install jest
          jest __generated_tests__/