# File: .github/workflows/cd.yml

name: CD

# Trigger on pushes to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js for Pages
        run: npm run pages:build

      - name: Authenticate with Cloudflare
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "$CF_API_TOKEN" | wrangler login --token

      - name: Deploy to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          npx wrangler pages deploy \
            --project-name my-next-app \
            --branch main \
            .vercel/output/static