# .github/workflows/ci-metrics.yml

name: CI Metrics & Dashboard

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 1. Lighthouse performance checks
  lighthouse:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Start app for Lighthouse
        run: npm run start & npx wait-on http://localhost:3001

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v8
        with:
          uploadArtifacts: true
          configPath: .lighthouserc.js

  # 2. Unit test coverage and upload to Codecov
  coverage:
    name: Unit Test Coverage
    runs-on: ubuntu-latest
    needs: lighthouse
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true