name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: production
      url: https://prod.yourapp.com
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Deploying to production..."