name: CI Performance Metrics

on:
  workflow_run:
    workflows: ["CI", "Advanced CI/CD & Security"]
    types: [completed]

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Collect Metrics via GitHub API
        uses: actions/github-script@v6
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            console.log(JSON.stringify({
              workflow: run.data.name,
              status: run.data.conclusion,
              duration: run.data.run_duration_ms
            }));
      - name: Push to InfluxDB
        run: |
          # Replace with your InfluxDB endpoint & token
          curl -XPOST $INFLUX_URL -H "Authorization: Token $INFLUX_TOKEN" \
            --data-binary "ci_metrics,workflow=${{ github.workflow }},status=${{ github.event.workflow_run.conclusion }} duration_ms=${{ steps.collect-metrics.outputs.duration }}"