name: CI Metrics Collection

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  collect-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Workflow Run Data
        uses: actions/github-script@v6
        with:
          script: |
            const run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            console.log("Workflow: " + run.data.name);
            console.log("Duration (ms): " + run.data.run_duration_ms);

      - name: Push to InfluxDB
        run: |
          curl -XPOST $INFLUX_URL -H "Authorization: Token $INFLUX_TOKEN" \
            --data-binary "ci_metrics,workflow=CI duration_ms=${{ steps.collect-metrics.outputs.duration }}"