name: Preview Deploy

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy Preview to Vercel
        id: vercel-preview
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: false
          comment: true

      - name: Notify Slack
        if: ${{ success() }}
        run: |
          curl -X POST -H 'Content-Type: application/json' \
          --data "{\"text\":\"🔃 Preview Deploy for PR ${{ github.event.number }}: ${{ steps.vercel-preview.outputs.preview-url }}\"}" \
          ${{ secrets.SLACK_WEBHOOK }}