name: Vault Secrets

on:
  workflow_call:

jobs:
  fetch-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Install Vault CLI
        run: |
          curl -fsSL https://releases.hashicorp.com/vault/1.13.0/vault_1.13.0_linux_amd64.zip -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/

      - name: Retrieve Dynamic Secret
        run: |
          export VAULT_ADDR=https://vault.example.com
          vault login -method=github token=${{ secrets.VAULT_GITHUB_TOKEN }}
          vault kv get -field=value secret/ci/nextjs > secret.txt

      - name: Use Secret
        run: |
          SECRET=$(cat secret.txt)
          echo "Secret: $SECRET"